name: Deploy to aaPanel (Local)

on:
  push:
    branches:
      - master  # ให้ทำงานเมื่อมี Push ไปที่ branch master

jobs:
  deploy:
    runs-on: self-hosted  # สั่งให้รันบนเครื่อง Ubuntu ของเราเอง

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy files to Web Root
        run: |
          # ยกเว้นการยุ่งกับ .git และ .user.ini ตอน rsync
          sudo rsync -avz --exclude='.git' --exclude='.user.ini' ./ /www/wwwroot/sitenews.com/
          
          # เปลี่ยน owner โดยยกเว้นไฟล์ .user.ini
          sudo find /www/wwwroot/sitenews.com/ -maxdepth 1 -name '.user.ini' -prune -o -exec chown -R www:www {} +